LanguageCatalog(
{
  "Mon": {
    "0": "၀",
    "1": "၁",
    "2": "၂",
    "3": "၃",
    "4": "၄",
    "5": "၅",
    "6": "၆",
    "7": "၇",
    "8": "၈",
    "9": "၉",
    "January": "ဂျာန်နျူအာရဳ",
    "February": "ဝှေဝ်ဗျူအာရဳ",
    "March": "မာတ်ချ်",
    "April": "ဨပြေယ်လ်",
    "May": "မေ",
    "June": "ဂျုန်",
    "July": "ဂျူလာဲ",
    "August": "အဝ်ဂါတ်",
    "September": "သိတ်ထဳဗာ",
    "October": "အံက်ထဝ်ဗာ",
    "November": "နဝ်ဝါမ်ဗာ",
    "December": "ဒဳဇြေန်ဗာ",
    "First Waso": "ဂိတုပ-ဒ္ဂိုန်",
    "Tagu": "စဲ",
    "Kason": "ပသာ်",
    "Nayon": "ဇှေ်",
    "Waso": "ဒ္ဂိုန်",
    "Wagaung": "ခ္ဍဲသဳ",
    "Tawthalin": "ဘတ်",
    "Thadingyut": "ဝှ်",
    "Tazaungmon": "က္ထိုန်",
    "Nadaw": "မြေက္ကသဵု",
    "Pyatho": "ပုဟ်",
    "Tabodwe": "မာ်",
    "Tabaung": "ဖဝ်ရဂိုန်",
    "waxing": "မံက်",
    "waning": "စွေက်",
    "full moon": "ပေၚ်",
    "new moon": "အိုတ်",
    "Myanmar Year": "သက္ကရာဇ်ဍုၚ်",
    "Ku": "သၞာံ",
    "Late": "",
    "Second": "ဒု",
    "Sunday": "အဒိုတ်",
    "Monday": "စန်",
    "Tuesday": "အၚာ",
    "Wednesday": "ဗုဒ္ဓဝါ",
    "Thursday": "ဗြဴဗတိ",
    "Friday": "သိုက်",
    "Saturday": "သ္ၚိသဝ်",
    "Nay": "",
    "Yat": "",
    "Sabbath Eve": "တ္ၚဲတိၚ်",
    "Sabbath": "တ္ၚဲသဳ",
    "Yatyaza": "ရာဇာ",
    "Afternoon Pyathada": "ရာဟု",
    "Pyathada": "ပြာဗ္ဗဒါ",
    "New Year Day": "New Year's Day",
    "Independence Day": "တ္ၚဲသၠးပွး",
    "Union Day": "တ္ၚဲကၟိန်ဍုၚ်",
    "Peasants Day": "တ္ၚဲသၟာဗ္ၚ",
    "Resistance Day": "တ္ၚဲပၠန်ဂတးဗၟာ",
    "Labour Day": "တ္ၚဲသၟာကမၠောန်",
    "Martyrs Day": "တ္ၚဲအာဇာနဲ",
    "Christmas Day": "တ္ၚဲခရေဿမာတ်",
    "Buddha Day": "တ္ၚဲသ္ဘၚ်ဖဍာ်ဇြဲ",
    "Start of Buddhist Lent": "တ္ၚဲတွံဓဝ်ဓမ္မစက်",
    "End of Buddhist Lent": "တ္ၚဲအဘိဓရ်",
    "Tazaungdaing": "သ္ဘၚ်ပူဇဴပၟတ်ပၞာၚ်",
    "National Day": "တ္ၚဲကောန်ဂကူဗၟာ",
    "Karen New Year Day": "ကရေၚ်လှာဲသၞာံ",
    "Tabaung Pwe": "သ္ဘၚ်ဖဝ်ရဂိုန်",
    "Thingyan Akyo": "တ္ၚဲဒစးအတး",
    "Thingyan Akya": "တ္ၚဲအတးစှေ်",
    "Thingyan Akyat": "တ္ၚဲအတးကြာပ်",
    "Thingyan Atat": "တ္ၚဲအတးတိုန်",
    "Myanmar New Year Day": "တ္ၚဲသၞာံတၟိ",
    "Amyeittasote": "ကိုန်အမြိုတ်",
    "Warameittugyi": "ကိုန်ဝါရမိတ္တုဇၞော်",
    "Warameittunge": "ကိုန်ဝါရမိတ္တုဍောတ်",
    "Thamaphyu": "ကိုန်လေၚ်ဒိုက်",
    "Thamanyo": "ကိုန်ဟုံဗြမ်",
    "Yatpote": "ကိုန်လီုလာ်",
    "Yatyotema": "ကိုန်ယုတ်မာ",
    "Mahayatkyan": "ကိုန်ဟွံခိုဟ်",
    "Nagapor": "နာ်မံက်",
    "Shanyat": "တ္ၚဲဒတန်",
    ",": "၊",
    ".": "။",
    "Mon National Day": "တ္ၚဲကောန်ဂကူမန်",
    "Mon Fallen Day": "တ္ၚဲဟံသာဝတဳလီု",
    "Mon Revolution Day": "တ္ၚဲပၠန်ဂတးမန်",
    "Mon Women Day": "တ္ၚဲညးဗြဴမန်",
    "G. Aung San BD": "တ္ၚဲသၟိၚ်ဗၟာ အံၚ်သာန်ဒှ်မၞိဟ်",
    "Valentines Day": "တ္ၚဲဝုတ်ဗၠာဲ",
    "Earth Day": "တ္ၚဲဂၠးကဝ်",
    "April Fools Day": "တ္ၚဲဨပြေယ်လ်သ္ပပရအ်",
    "Red Cross Day": "တ္ၚဲဇိုၚ်ခ္ဍာ်ဍာဲ",
    "United Nations Day": "တ္ၚဲကုလသမ္မဂ္ဂ",
    "Halloween": "တ္ၚဲဟေဝ်လဝ်ဝိန်",
    "Shan New Year Day": "တ္ၚဲသေံလှာဲသၞာံ",
    "Mothers Day": "တ္ၚဲမိအံက်",
    "Fathers Day": "တ္ၚဲမအံက်",
    "Sasana Year": "သက္ကရာဇ် သာသနာ",
    "Eid": "အိဒ်",
    "Diwali": "ဒဳဝါလဳ",
    "Mahathamaya Day": "တ္ၚဲမဟာသမယ",
    "Garudhamma Day": "တ္ၚဲဂရုဓမ္မ",
    "Metta Day": "တ္ၚဲမေတ္တာ",
    "Taungpyone Pwe": "တောင်ပြုန်းပွဲ",
    "Yadanagu Pwe": "ရတနာ့ဂူပွဲ",
    "Authors Day": "စာဆိုတော်နေ့",
    "World Teachers Day": "ကမ္ဘာ့ဆရာများနေ့",
    "Holiday": "တ္ၚဲတၟာတ်ရုၚ်",
    "Chinese New Year": "တရုတ်နှစ်သစ်ကူး",
    "Easter": "ထမြောက်ရာနေ့",
    "Good Friday": "သောကြာနေ့ကြီး",
	"Mon Youth Day": "တ္ၚဲသၟတ်မန်",
	"Mon Sasana Day": "တ္ၚဲဂကူမန်ဆဵုကျာ်တြဲကၠာအိုတ်",
	"Mon National Blood Day": "တ္ၚဲကဵုဒါန်ဆီဂကူမန်"
  },
  "English": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "First Waso": "First Waso",
    "Tagu": "Tagu",
    "Kason": "Kason",
    "Nayon": "Nayon",
    "Waso": "Waso",
    "Wagaung": "Wagaung",
    "Tawthalin": "Tawthalin",
    "Thadingyut": "Thadingyut",
    "Tazaungmon": "Tazaungmon",
    "Nadaw": "Nadaw",
    "Pyatho": "Pyatho",
    "Tabodwe": "Tabodwe",
    "Tabaung": "Tabaung",
    "waxing": "waxing",
    "waning": "waning",
    "full moon": "full moon",
    "new moon": "new moon",
    "Myanmar Year": "Myanmar Year",
    "Ku": " ",
    "Late": "Late ",
    "Second": "Second ",
    "Sunday": "Sunday",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "Nay": " ",
    "Yat": " ",
    "Sabbath Eve": "Sb Eve",
    "Sabbath": "Sabbath",
    "Yatyaza": "Yatyaza",
    "Afternoon Pyathada": "Afternoon Pyathada",
    "Pyathada": "Pyathada",
    "New Year Day": "New Year's Day",
    "Independence Day": "Independence Day",
    "Union Day": "Union Day",
    "Peasants Day": "Peasants Day",
    "Resistance Day": "Resistance Day",
    "Labour Day": "Labour Day",
    "Martyrs Day": "Martyrs' Day",
    "Christmas Day": "Christmas Day",
    "Buddha Day": "Buddha Day",
    "Start of Buddhist Lent": "Start of Buddhist Lent",
    "End of Buddhist Lent": "End of Buddhist Lent",
    "Tazaungdaing": "Tazaungdaing",
    "National Day": "National Day",
    "Karen New Year Day": "Karen New Year Day",
    "Tabaung Pwe": "Tabaung Pwe",
    "Thingyan Akyo": "Thingyan Akyo",
    "Thingyan Akya": "Thingyan Akya",
    "Thingyan Akyat": "Thingyan Akyat",
    "Thingyan Atat": "Thingyan Atat",
    "Myanmar New Year Day": "Myanmar New Year Day",
    "Amyeittasote": "Amyeittasote",
    "Warameittugyi": "Warameittugyi",
    "Warameittunge": "Warameittunge",
    "Thamaphyu": "Thamaphyu",
    "Thamanyo": "Thamanyo",
    "Yatpote": "Yatpote",
    "Yatyotema": "Yatyotema",
    "Mahayatkyan": "Mahayatkyan",
    "Nagapor": "Nagapor",
    "Shanyat": "Shanyat",
    ",": ",",
    ".": ".",
    "Mon National Day": "Mon National Day",
    "Mon Fallen Day": "Mon Fallen Day",
    "Mon Revolution Day": "Mon Revolution Day",
    "Mon Women Day": "Mon Women Day",
    "G. Aung San BD": "G. Aung San BD",
    "Valentines Day": "Valentines Day",
    "Earth Day": "Earth Day",
    "April Fools Day": "April Fools' Day",
    "Red Cross Day": "Red Cross Day",
    "United Nations Day": "United Nations Day",
    "Halloween": "Halloween",
    "Shan New Year Day": "Shan New Year Day",
    "Mothers Day": "Mothers' Day",
    "Fathers Day": "Fathers' Day",
    "Sasana Year": "Sasana Year",
    "Eid": "Eid",
    "Diwali": "Diwali",
    "Mahathamaya Day": "Great Integration",
    "Garudhamma Day": "Garudhamma Day",
    "Metta Day": "Metta Day",
    "Taungpyone Pwe": "Taungpyone Pwe",
    "Yadanagu Pwe": "Yadanagu Pwe",
    "Authors Day": "Authors' Day",
    "World Teachers Day": "World Teachers' Day",
    "Holiday": "Holiday",
    "Chinese New Year": "Chinese New Year",
    "Easter": "Easter",
    "Good Friday": "Good Friday",
	"Mon Youth Day": "Mon Youth Day",
	"Mon Sasana Day": "Mon Sasana Day",
	"Mon National Blood Day": "Mon National Blood Day"
  },
  "Myanmar": {
    "0": "၀",
    "1": "၁",
    "2": "၂",
    "3": "၃",
    "4": "၄",
    "5": "၅",
    "6": "၆",
    "7": "၇",
    "8": "၈",
    "9": "၉",
    "January": "ဇန်နဝါရီ",
    "February": "ဖေဖော်ဝါရီ",
    "March": "မတ်",
    "April": "ဧပြီ",
    "May": "မေ",
    "June": "ဇွန်",
    "July": "ဇူလိုင်",
    "August": "ဩဂုတ်",
    "September": "စက်တင်ဘာ",
    "October": "အောက်တိုဘာ",
    "November": "နိုဝင်ဘာ",
    "December": "ဒီဇင်ဘာ",
    "First Waso": "ပဝါဆို",
    "Tagu": "တန်ခူး",
    "Kason": "ကဆုန်",
    "Nayon": "နယုန်",
    "Waso": "ဝါဆို",
    "Wagaung": "ဝါခေါင်",
    "Tawthalin": "တော်သလင်း",
    "Thadingyut": "သီတင်းကျွတ်",
    "Tazaungmon": "တန်ဆောင်မုန်း",
    "Nadaw": "နတ်တော်",
    "Pyatho": "ပြာသို",
    "Tabodwe": "တပို့တွဲ",
    "Tabaung": "တပေါင်း",
    "waxing": "လဆန်း",
    "waning": "လဆုတ်",
    "full moon": "လပြည့်",
    "new moon": "လကွယ်",
    "Myanmar Year": "မြန်မာနှစ်",
    "Ku": "ခု",
    "Late": "နှောင်း",
    "Second": "ဒု",
    "Sunday": "တနင်္ဂနွေ",
    "Monday": "တနင်္လာ",
    "Tuesday": "အင်္ဂါ",
    "Wednesday": "ဗုဒ္ဓဟူး",
    "Thursday": "ကြာသပတေး",
    "Friday": "သောကြာ",
    "Saturday": "စနေ",
    "Nay": "နေ့",
    "Yat": "ရက်",
    "Sabbath Eve": "အဖိတ်",
    "Sabbath": "ဥပုသ်",
    "Yatyaza": "ရက်ရာဇာ",
    "Afternoon Pyathada": "မွန်းလွဲပြဿဒါး",
    "Pyathada": "ပြဿဒါး",
    "New Year Day": "New Year's Day",
    "Independence Day": "လွတ်လပ်ရေးနေ့",
    "Union Day": "ပြည်ထောင်စုနေ့",
    "Peasants Day": "တောင်သူ လယ်သမားနေ့",
    "Resistance Day": "တော်လှန်ရေးနေ့",
    "Labour Day": "အလုပ်သမားနေ့",
    "Martyrs Day": "အာဇာနည်နေ့",
    "Christmas Day": "ခရစ္စမတ်နေ့",
    "Buddha Day": "ညောင်ရေသွန်းပွဲ",
    "Start of Buddhist Lent": "ဓမ္မစကြာနေ့",
    "End of Buddhist Lent": "မီးထွန်းပွဲ",
    "Tazaungdaing": "တန်ဆောင်တိုင်",
    "National Day": "အမျိုးသားနေ့",
    "Karen New Year Day": "ကရင်နှစ်သစ်ကူး",
    "Tabaung Pwe": "တပေါင်းပွဲ",
    "Thingyan Akyo": "သင်္ကြန်အကြို",
    "Thingyan Akya": "သင်္ကြန်အကျ",
    "Thingyan Akyat": "သင်္ကြန်အကြတ်",
    "Thingyan Atat": "သင်္ကြန်အတက်",
    "Myanmar New Year Day": "နှစ်ဆန်းတစ်ရက်",
    "Amyeittasote": "အမြိတ္တစုတ်",
    "Warameittugyi": "ဝါရမိတ္တုကြီး",
    "Warameittunge": "ဝါရမိတ္တုငယ်",
    "Thamaphyu": "သမားဖြူ",
    "Thamanyo": "သမားညို",
    "Yatpote": "ရက်ပုပ်",
    "Yatyotema": "ရက်ယုတ်မာ",
    "Mahayatkyan": "မဟာရက်ကြမ်း",
    "Nagapor": "နဂါးပေါ်",
    "Shanyat": "ရှမ်းရက်",
    ",": "၊",
    ".": "။",
    "Mon National Day": "မွန်အမျိုးသားနေ့",
    "Mon Fallen Day": "ဟံသာဝတီပျက်သုဉ်းနေ့",
    "Mon Revolution Day": "မွန်တော်လှန်ရေးနေ့",
    "Mon Women Day": "မွန်အမျိုးသမီးနေ့",
    "G. Aung San BD": "ဗိုလ်ချုပ်မွေးနေ့",
    "Valentines Day": "ချစ်သူများနေ့",
    "Earth Day": "ကမ္ဘာမြေနေ့",
    "April Fools Day": "ဧပြီအရူးနေ့",
    "Red Cross Day": "ကြက်ခြေနီနေ့",
    "United Nations Day": "ကုလသမ္မဂ္ဂနေ့",
    "Halloween": "သရဲနေ့",
    "Shan New Year Day": "ရှမ်းနှစ်သစ်ကူး",
    "Mothers Day": "အမေနေ့",
    "Fathers Day": "အဖေနေ့",
    "Sasana Year": "သာသနာနှစ်",
    "Eid": "အိဒ်",
    "Diwali": "ဒီဝါလီ",
    "Mahathamaya Day": "မဟာသမယနေ့",
    "Garudhamma Day": "ဂရုဓမ္မနေ့",
    "Metta Day": "မေတ္တာနေ့",
    "Taungpyone Pwe": "တောင်ပြုန်းပွဲ",
    "Yadanagu Pwe": "ရတနာ့ဂူပွဲ",
    "Authors Day": "စာဆိုတော်နေ့",
    "World Teachers Day": "ကမ္ဘာ့ဆရာများနေ့",
    "Holiday": "ရုံးပိတ်ရက်",
    "Chinese New Year": "တရုတ်နှစ်သစ်ကူး",
    "Easter": "ထမြောက်ရာနေ့",
    "Good Friday": "သောကြာနေ့ကြီး",
	"Mon Youth Day": "မွန်လူငယ်နေ့",
	"Mon Sasana Day": "မွန်လူမျိုးတို့၏ ဦးစွာဗုဒ္ဓဖူးမြင်သောနေ့",
	"Mon National Blood Day": "မွန်အမျိုးသားသွေးလှူဒါန်းနေ့"
  },
  "NMon": {
    "0": "၀",
    "1": "၁",
    "2": "၂",
    "3": "၃",
    "4": "၄",
    "5": "၅",
    "6": "၆",
    "7": "၇",
    "8": "၈",
    "9": "၉",
    "January": "ဂ်ာန္န်ဴအာရ႘",
    "February": "ေဝွဝ္ဗ်ဴအာရ႘",
    "March": "မာတ္ခ်္",
    "April": "ဨေျပယ္လ္",
    "May": "ေမ",
    "June": "ဂ်ဳန္",
    "July": "ဂ်ဴလာဲ",
    "August": "အဝ္ဂါတ္",
    "September": "သိတ္ထ႘ဗာ",
    "October": "အံက္ထဝ္ဗာ",
    "November": "နဝ္ဝါမ္ဗာ",
    "December": "ဒ႘ေျဇန္ဗာ",
    "First Waso": "ပ-ဒၢိဳန္",
    "Tagu": "စဲ",
    "Kason": "ပသာ္",
    "Nayon": "ေဇွ္",
    "Waso": "ဒၢိဳန္",
    "Wagaung": "ခႜဲသ႘",
    "Tawthalin": "ဘတ္",
    "Thadingyut": "ဝွ္",
    "Tazaungmon": "ကၳိဳန္",
    "Nadaw": "ေျမကၠသႝု",
    "Pyatho": "ပုဟ္",
    "Tabodwe": "မာ္",
    "Tabaung": "ဖဝ္ရဂိုန္",
    "waxing": "မံက္",
    "waning": "ေစြက္",
    "full moon": "ေပင္",
    "new moon": "အိုတ္",
    "Myanmar Year": "သကၠရာဇ္ဍဳင္",
    "Ku": "သှာံ",
    "Late": "",
    "Second": "ဒု",
    "Sunday": "အဒိုတ္",
    "Monday": "စန္",
    "Tuesday": "အငၛာ",
    "Wednesday": "ဗုဒၶဝါ",
    "Thursday": "ၿဗဵဗတိ",
    "Friday": "သိုက္",
    "Saturday": "သၛိသဝ္",
    "Nay": "",
    "Yat": "",
    "Sabbath Eve": "တၛဲတိင္",
    "Sabbath": "တၛဲသ႘",
    "Yatyaza": "ရာဇာ",
    "Afternoon Pyathada": "ရာဟု",
    "Pyathada": "ျပာဗၺဒါ",
    "New Year Day": "New Year's Day",
    "Independence Day": "သၜးပြး",
    "Union Day": "တၛဲကဿိန္ဍဳင္",
    "Peasants Day": "တၛဲသဿာဗၛ",
    "Resistance Day": "တၛဲပၜန္ဂတးဗဿာ",
    "Labour Day": "တၛဲသဿာကေမၜာန္",
    "Martyrs Day": "တၛဲအာဇာနဲ",
    "Christmas Day": "တၛဲခေရႆမာတ္",
    "Buddha Day": "တၛဲသၻင္ဖဍာ္ၿဇဲ",
    "Start of Buddhist Lent": "တၛဲတြံဓဝ္ဓမၼစက္",
    "End of Buddhist Lent": "တၛဲအဘိဓရ္",
    "Tazaungdaing": "သၻင္ပူဇဵပဿတ္ပှာင္",
    "National Day": "တၛဲေကာန္ဂကူဗဿာ",
    "Karen New Year Day": "ကေရင္လွာဲသှာံ",
    "Tabaung Pwe": "သၻင္ဖဝ္ရဂိုန္",
    "Thingyan Akyo": "တၛဲဒစးအတး",
    "Thingyan Akya": "တၛဲအတးေစွ္",
    "Thingyan Akyat": "တၛဲအတးၾကာပ္",
    "Thingyan Atat": "တၛဲအတးတိုန္",
    "Myanmar New Year Day": "တၛဲသှာံတဿိ",
    "Amyeittasote": "ကိုန္အၿမိဳတ္",
    "Warameittugyi": "ကိုန္ဝါရမိတၱဳေဇှာ္",
    "Warameittunge": "ကိုန္ဝါရမိတၱဳေဍာတ္",
    "Thamaphyu": "ကိုန္ေလင္ဒိုက္",
    "Thamanyo": "ကိုန္ဟုံျဗမ္",
    "Yatpote": "ကိုန္လီုလာ္",
    "Yatyotema": "ကိုန္ယုတ္မာ",
    "Mahayatkyan": "ကိုန္ဟြံခိုဟ္",
    "Nagapor": "နာ္မံက္",
    "Shanyat": "တၛဲဒတန္",
    ",": "၊",
    ".": "။",
    "Mon National Day": "တၛဲေကာန္ဂကူမန္",
    "Mon Fallen Day": "တၛဲဟံသာဝတ႘လီု",
    "Mon Revolution Day": "တၛဲပၜန္ဂတးမန္",
    "Mon Women Day": "တၛဲညးၿဗဵမန္",
    "G. Aung San BD": "တၛဲသဿိင္ဗဿာ အံင္သာန္ဒွ္မှိဟ္",
    "Valentines Day": "တၛဲဝုတ္ဗၜာဲ",
    "Earth Day": "တၛဲဂၜးကဝ္",
    "April Fools Day": "တၛဲဨပြေယ်လ်သၸပရအ္",
    "Red Cross Day": "တၛဲဇိုင္ခႜာ္ဍာဲ",
    "United Nations Day": "တၛဲကုလသမၼဂၢ",
    "Halloween": "တၛဲေဟဝ္လဝ္ဝိန္",
    "Shan New Year Day": "တၛဲေသံလွာဲသှာံ",
    "Mothers Day": "တၛဲမိအံက္",
    "Fathers Day": "တၛဲမအံက္",
    "Sasana Year": "သကၠရာဇ္ သာသနာ",
    "Eid": "အိဒ္",
    "Diwali": "ဒ႘ဝါလ႘",
    "Mahathamaya Day": "တၛဲမဟာသမယ",
    "Garudhamma Day": "တၛဲဂ႐ုဓမၼ",
    "Metta Day": "တၛဲေမတၱာ",
    "Taungpyone Pwe": "ေတာင္ျပဳန္းပြဲ",
    "Yadanagu Pwe": "ရတနာ့ဂူပြဲ",
    "Authors Day": "စာဆိုေတာ္ေန႔",
    "World Teachers Day": "ကမၻာ့ဆရာမ်ားေန႔",
    "Holiday": "တၛဲတဿာတ္႐ုင္",
    "Chinese New Year": "တ႐ုတ္ႏွစ္သစ္ကူး",
    "Easter": "ထေျမာက္ရာေန႔",
    "Good Friday": "ေသာၾကာေန႔ႀကီး",
	"Mon Youth Day": "တၛဲသဿတ္မန္",
	"Mon Sasana Day": "တၛဲဂကူမန္ဆႝုက်ာ္ႀတဲကၜာအိုတ္",
	"Mon National Blood Day": "တၛဲကႝုဒါန္ဆီဂကူမန္"
  },
  "UniMon": {
    "0": "၀",
    "1": "၁",
    "2": "၂",
    "3": "၃",
    "4": "၄",
    "5": "၅",
    "6": "၆",
    "7": "၇",
    "8": "၈",
    "9": "၉",
    "January": "ဂ်ာန္ႏ်ဴအာရွ",
    "February": "ေဝွဝ္ဗ်ဴအာရွ",
    "March": "မာတ္ခ်္",
    "April": "ဨေျပယ္လ္",
    "May": "ေမ",
    "June": "ဂ်ဳန္",
    "July": "ဂ်ဴလာဲ",
    "August": "အဝ္ဂါတ္",
    "September": "သိတ္ထွဗာ",
    "October": "အံက္ထဝ္ဗာ",
    "November": "နဝ္ဝါမ္ဗာ",
    "December": "ဒွေျဇန္ဗာ",
    "First Waso": "ပ-ဒၢိဳန္",
    "Tagu": "စဲ",
    "Kason": "ပသာ္",
    "Nayon": "ေဇွ္",
    "Waso": "ဒၢိဳန္",
    "Wagaung": "ခႛဲသှ",
    "Tawthalin": "ဘတ္",
    "Thadingyut": "ဝွ္",
    "Tazaungmon": "ကၳိဳန္",
    "Nadaw": "ေျမကၠသဪု",
    "Pyatho": "ပုဟ္",
    "Tabodwe": "မာ္",
    "Tabaung": "ဖဝ္ရဂိုန္",
    "waxing": "မံက္",
    "waning": "ေစြက္",
    "full moon": "ေပင္",
    "new moon": "အိုတ္",
    "Myanmar Year": "သကၠရာဇ္ဍဳင္",
    "Ku": "သႝာံ",
    "Late": "",
    "Second": "ဒု",
    "Sunday": "အဒိုတ္",
    "Monday": "စန္",
    "Tuesday": "အငၝာ",
    "Wednesday": "ဗုဒၶဝါ",
    "Thursday": "ၿဗၜဗတိ",
    "Friday": "သိုက္",
    "Saturday": "သၝိသဝ္",
    "Nay": "",
    "Yat": "",
    "Sabbath Eve": "တၝဲတိင္",
    "Sabbath": "တၝဲသှ",
    "Yatyaza": "ရာဇာ",
    "Afternoon Pyathada": "ရာဟု",
    "Pyathada": "ျပာဗၺဒါ",
    "New Year Day": "New Year's Day",
    "Independence Day": "တၝဲသႜးပြး",
    "Union Day": "တၝဲကၞိန္ဍဳင္",
    "Peasants Day": "တၝဲသၞာဗၝ",
    "Resistance Day": "တၝဲပႜန္ဂတးဗၞာ",
    "Labour Day": "တၝဲသၞာကေမႜာန္",
    "Martyrs Day": "တၝဲအာဇာနဲ",
    "Christmas Day": "တၝဲခေရႆမာတ္",
    "Buddha Day": "တၝဲသၻင္ဖဍာ္ၿဇဲ",
    "Start of Buddhist Lent": "တၝဲတြံဓဝ္ဓမၼစက္",
    "End of Buddhist Lent": "တၝဲအဘိဓရ္",
    "Tazaungdaing": "သၻင္ပူဇၜပၞတ္ပႝာင္",
    "National Day": "တၝဲေကာန္ဂကူဗၞာ",
    "Karen New Year Day": "ကေရင္လွာဲသႝာံ",
    "Tabaung Pwe": "သၻင္ဖဝ္ရဂိုန္",
    "Thingyan Akyo": "တၝဲဒစးအတး",
    "Thingyan Akya": "တၝဲအတးေစွ္",
    "Thingyan Akyat": "တၝဲအတးၾကာပ္",
    "Thingyan Atat": "တၝဲအတးတိုန္",
    "Myanmar New Year Day": "တၝဲသႝာံတၞိ",
    "Amyeittasote": "ကိုန္အၿမိဳတ္",
    "Warameittugyi": "ကိုန္ဝါရမိတၱဳေဇႝာ္",
    "Warameittunge": "ကိုန္ဝါရမိတၱဳေဍာတ္",
    "Thamaphyu": "ကိုန္ေလင္ဒိုက္",
    "Thamanyo": "ကိုန္ဟုံျဗမ္",
    "Yatpote": "ကိုန္လီုလာ္",
    "Yatyotema": "ကိုန္ယုတ္မာ",
    "Mahayatkyan": "ကိုန္ဟြံခိုဟ္",
    "Nagapor": "နာ္မံက္",
    "Shanyat": "တၝဲဒတန္",
    ",": "၊",
    ".": "။",
    "Mon National Day": "တၝဲေကာန္ဂကူမန္",
    "Mon Fallen Day": "တၝဲဟံသာဝတွလီု",
    "Mon Revolution Day": "တၝဲပႜန္ဂတးမန္",
    "Mon Women Day": "တၝဲညးၿဗၜမန္",
    "G. Aung San BD": "တၝဲသၞိင္ဗၞာ အံင္သာန္ဒွ္မႝိဟ္",
    "Valentines Day": "တၝဲဝုတ္ဗႜာဲ",
    "Earth Day": "တၝဲဂႜးကဝ္",
    "April Fools Day": "တၝဲဨေျပယ္လ္သၸပရအ္",
    "Red Cross Day": "တၝဲဇိုင္ခႛာ္ဍာဲ",
    "United Nations Day": "တၝဲကုလသမၼဂၢ",
    "Halloween": "တၝဲေဟဝ္လဝ္ဝိန္",
    "Shan New Year Day": "တၝဲေသံလွာဲသႝာံ",
    "Mothers Day": "တၝဲမိအံက္",
    "Fathers Day": "တၝဲမအံက္",
    "Sasana Year": "သကၠရာဇ္ သာသနာ",
    "Eid": "အိဒ္",
    "Diwali": "ဒွဝါလွ",
    "Mahathamaya Day": "တၝဲမဟာသမယ",
    "Garudhamma Day": "တၝဲဂ႐ုဓမၼ",
    "Metta Day": "တၝဲေမတၱာ",
    "Taungpyone Pwe": "ေတာင္ၿပဳန္းပြဲ",
    "Yadanagu Pwe": "ရတနာ့ဂူပြဲ",
    "Authors Day": "စာဆိုေတာ္ေန႔",
    "World Teachers Day": "ကမၻာ့ဆရာမ်ားေန႔",
    "Holiday": "တၝဲတၞာတ္႐ုင္",
    "Chinese New Year": "တ႐ုတ္ႏွစ္သစ္ကူး",
    "Easter": "ထေျမာက္ရာေန႔",
    "Good Friday": "ေသာၾကာေန႔ႀကီး",
	"Mon Youth Day": "တၝဲသၞတ္မန္",
	"Mon Sasana Day": "တၝဲဂကူမန္ဆဪုက်ာ္ႀတဲကႜာအိုတ္",
	"Mon National Blood Day": "တၝဲကဪုဒါန္ဆီဂကူမန္"
  },
  "Zawgyi": {
    "0": "၀",
    "1": "၁",
    "2": "၂",
    "3": "၃",
    "4": "၄",
    "5": "၅",
    "6": "၆",
    "7": "၇",
    "8": "၈",
    "9": "၉",
    "January": "ဇန္နဝါရီ",
    "February": "ေဖေဖာ္ဝါရီ",
    "March": "မတ္",
    "April": "ဧၿပီ",
    "May": "ေမ",
    "June": "ဇြန္",
    "July": "ဇူလိုင္",
    "August": "ဩဂုတ္",
    "September": "စက္တင္ဘာ",
    "October": "ေအာက္တိုဘာ",
    "November": "နိုဝင္ဘာ",
    "December": "ဒီဇင္ဘာ",
    "First Waso": "ပဝါဆို",
    "Tagu": "တန္ခူး",
    "Kason": "ကဆုန္",
    "Nayon": "နယုန္",
    "Waso": "ဝါဆို",
    "Wagaung": "ဝါေခါင္",
    "Tawthalin": "ေတာ္သလင္း",
    "Thadingyut": "သီတင္းကြ်တ္",
    "Tazaungmon": "တန္ေဆာင္မုန္း",
    "Nadaw": "နတ္ေတာ္",
    "Pyatho": "ျပာသို",
    "Tabodwe": "တပို႔တြဲ",
    "Tabaung": "တေပါင္း",
    "waxing": "လဆန္း",
    "waning": "လဆုတ္",
    "full moon": "လျပည့္",
    "new moon": "လကြယ္",
    "Myanmar Year": "ျမန္မာႏွစ္",
    "Ku": "ခု",
    "Late": "ေႏွာင္း",
    "Second": "ဒု",
    "Sunday": "တနဂၤေႏြ",
    "Monday": "တနလၤာ",
    "Tuesday": "အဂၤါ",
    "Wednesday": "ဗုဒၶဟူး",
    "Thursday": "ၾကာသပေတး",
    "Friday": "ေသာၾကာ",
    "Saturday": "စေန",
    "Nay": "ေန႔",
    "Yat": "ရက္",
    "Sabbath Eve": "အဖိတ္",
    "Sabbath": "ဥပုသ္",
    "Yatyaza": "ရက္ရာဇာ",
    "Afternoon Pyathada": "မြန္းလြဲျပႆဒါး",
    "Pyathada": "ျပႆဒါး",
    "New Year Day": "New Year's Day",
    "Independence Day": "လြတ္လပ္ေရးေန႔",
    "Union Day": "ျပည္ေထာင္စုေန႔",
    "Peasants Day": "ေတာင္သူ လယ္သမားေန႔",
    "Resistance Day": "ေတာ္လွန္ေရးေန႔",
    "Labour Day": "အလုပ္သမားေန႔",
    "Martyrs Day": "အာဇာနည္ေန႔",
    "Christmas Day": "ခရစၥမတ္ေန႔",
    "Buddha Day": "ေညာင္ေရ သြန္းပြဲ",
    "Start of Buddhist Lent": "ဓမၼစၾကာေန႔",
    "End of Buddhist Lent": "မီးထြန္းပြဲ",
    "Tazaungdaing": "တန္ေဆာင္တိုင္",
    "National Day": "အမ်ိဳးသားေန႔",
    "Karen New Year Day": "ကရင္ နွစ္သစ္ကူး",
    "Tabaung Pwe": "တေပါင္းပြဲ",
    "Thingyan Akyo": "သၾကၤန္ အႀကိဳ",
    "Thingyan Akya": "သႀကၤန္္ အက်",
    "Thingyan Akyat": "သႀကၤန္္ အၾကတ္",
    "Thingyan Atat": "သႀကၤန္္ အတက္",
    "Myanmar New Year Day": "နွစ္ဆန္း တစ္ရက္",
    "Amyeittasote": "အၿမိတၱစုတ္",
    "Warameittugyi": "ဝါရမိတၱဳႀကီး",
    "Warameittunge": "ဝါရမိတၱဳငယ္",
    "Thamaphyu": "သမားျဖဴ",
    "Thamanyo": "သမားညိဳ",
    "Yatpote": "ရက္ပုပ္",
    "Yatyotema": "ရက္ယုတ္မာ",
    "Mahayatkyan": "မဟာရက္ၾကမ္း",
    "Nagapor": "နဂါးေပၚ",
    "Shanyat": "ရွမ္းရက္",
    ",": "၊",
    ".": "။",
    "Mon National Day": "မြန္အမ်ိဳးသားေန႔",
    "Mon Fallen Day": "ဟံသာဝတီပ်က္သုဥ္းေန႔",
    "Mon Revolution Day": "မြန္ေတာ္လွန္ေရးေန႔",
    "Mon Women Day": "မြန္အမ်ိဳးသမီးေန႔",
    "G. Aung San BD": "ဗိုလ္ခ်ဳပ္ေမြးေန႔",
    "Valentines Day": "ခ်စ္သူမ်ားေန႔",
    "Earth Day": "ကမၻာေျမေန႔",
    "April Fools Day": "ဧၿပီအ႐ူးေန႔",
    "Red Cross Day": "ၾကက္ေျခနီေန႔",
    "United Nations Day": "ကုလသမၼဂၢေန႔",
    "Halloween": "သရဲေန႔",
    "Shan New Year Day": "ရွမ္းနွစ္သစ္ကူး",
    "Mothers Day": "အေမေန႔",
    "Fathers Day": "အေဖေန႔",
    "Sasana Year": "သာသနာႏွစ္",
    "Eid": "အိဒ္",
    "Diwali": "ဒီဝါလီ",
    "Mahathamaya Day": "မဟာသမယေန႔",
    "Garudhamma Day": "ဂ႐ုဓမၼေန႔",
    "Metta Day": "ေမတၱာေန႔",
    "Taungpyone Pwe": "ေတာင္ျပဳန္းပြဲ",
    "Yadanagu Pwe": "ရတနာ့ဂူပြဲ",
    "Authors Day": "စာဆိုေတာ္ေန႔",
    "World Teachers Day": "ကမၻာ့ဆရာမ်ားေန႔",
    "Holiday": "႐ုံးပိတ္ရက္",
    "Chinese New Year": "တ႐ုတ္ႏွစ္သစ္ကူး",
    "Easter": "ထေျမာက္ရာေန႔",
    "Good Friday": "ေသာၾကာေန႔ႀကီး",
	"Mon Youth Day": "မြန္လူငယ္ေန႔",
	"Mon Sasana Day": "မြန္လူမ်ိဳးတို႔၏ ဦးစြာဗုဒၶဖူးျမင္ေသာေန႔",
	"Mon National Blood Day": "မြန္အမ်ိဳးသားေသြးလွဴဒါန္းေန႔"
  }
}
);
